// Educational explanations are separate from observations about a repository.
const swift = 'https://docs.swift.org/swift-book/LanguageGuide/Concurrency.html';
const task = 'https://developer.apple.com/documentation/swift/task';
const group = 'https://developer.apple.com/documentation/swift/taskgroup';
export const definitions = {
  task: {title:'an unstructured Task', meaning:'Task { … } starts work without a structured parent. Creating it inside another Task does not make it a structured child.', detail:'It can inherit actor context, priority and task-local values, but not automatic cancellation from its creator. Keeping its handle lets you await or cancel it; dropping the handle does not stop it.', choice:'Use it to enter asynchronous work from a button, or for independently owned work. Use child tasks when the work belongs to an existing task. For checkout, ignoring duplicate requests is usually more appropriate than cancelling the purchase.', source:task},
  detached: {title:'a detached Task', meaning:'Task.detached { … } creates an unstructured Task without inheriting the caller’s actor context or task-local values.', detail:'Cancellation is not automatically forwarded from its creator. Detached does not mean a dedicated thread.', choice:'Use only when independence from the caller’s context is intentional. It is not a default way to make work asynchronous.', source:task},
  'async-let': {title:'a structured child Task', meaning:'async let and task-group additions create children of the current task. Their work cannot outlive the enclosing structured scope.', detail:'Parent cancellation propagates to children, but each child must cooperate. Scope completion waits for children to finish.', choice:'Use async let for a known set of related operations. Use a task group when the number of operations varies.', source:group},
  group: {title:'a task group', meaning:'A scope for creating and awaiting a collection of structured child Tasks.', detail:'The group itself is not another Task. Adding work creates children; leaving the scope waits for them. Cancellation is cooperative.', choice:'Useful for a variable number of related operations. Child Tasks may run concurrently, but simultaneous execution is not guaranteed.', source:group},
  'group-child': {title:'a task-group child', meaning:'Calling addTask on a Swift task group creates a structured child Task.', detail:'A loop can create many children from one line of code. This scanner must still verify that the receiver is a real task group.', choice:'Use for related work whose completion belongs to the enclosing task-group scope.', source:group},
  await: {title:'await', meaning:'A point where the current Task may pause while waiting for a result. It does not create another Task.', detail:'Pausing releases execution capacity instead of blocking a thread. An await does not guarantee that a pause actually occurs.', choice:'Call an async function directly with await when you do not need another Task.', source:swift},
  'main-actor': {title:'MainActor', meaning:'The shared actor used to coordinate UI work on the main thread.', detail:'It protects isolated state, but a method can suspend and allow other work to run. An annotation count does not measure how much work runs there.', choice:'Keep UI updates and short state changes here. Inspect expensive work separately; observable state is not itself a performance problem.', source:'https://developer.apple.com/documentation/swift/mainactor'},
  'view-task': {title:'SwiftUI .task', meaning:'SwiftUI creates and manages a Task associated with the View’s lifetime.', detail:'Leaving that lifetime requests cancellation. With .task(id:), changing the ID cancels the previous Task and starts another. Cancellation is cooperative: old work may still be finishing when replacement work starts. Cancellation does not undo a write already accepted by storage or a server.', choice:'Useful for work needed while a View is displayed. Trace saves carefully: committed work may need an independently owned lifetime. An ordinary Button Task is different—another press does not automatically cancel it.', source:'https://developer.apple.com/documentation/swiftui/view/task(id:priority:_:)'},
  refresh: {title:'SwiftUI .refreshable', meaning:'Supplies asynchronous work for a refresh action, such as pulling down a list.', detail:'Await the refresh operation so the refresh UI follows its completion.', choice:'Usually call the refresh function directly with await rather than starting a separate Task and returning immediately.', source:'https://developer.apple.com/documentation/swiftui/view/refreshable(action:)'},
  cancellation: {title:'cooperative cancellation', meaning:'Cancellation asks a Task to stop; it does not forcibly terminate its execution.', detail:'The code checks cancellation or calls an operation that responds to it. Keeping a handle does not itself cancel anything.', choice:'Choose a policy: cancel obsolete searches, ignore duplicate checkouts, or queue edits that must all finish.', source:swift},
  parallel: {title:'concurrent versus parallel work', meaning:'Concurrent operations can make progress during the same period. Parallel operations execute at the same instant.', detail:'Source code can permit concurrency without proving runtime parallelism.', choice:'Use runtime evidence to measure overlap. Do not interpret a child-task count as a parallelism measurement.', source:swift},
  sequential: {title:'sequential awaits', meaning:'In a straight-line sequence, one awaited call returns before the next call begins.', detail:'Other Tasks may run while this Task waits. Awaiting two already-started Tasks in order does not mean their work ran sequentially.', choice:'Use a sequence when the second operation needs the first result. Consider children for independent, related work.', source:swift},
  gcd: {title:'Dispatch scheduling', meaning:'Work submitted to a Dispatch queue rather than created using Swift Task syntax.', detail:'A serial queue and an actor do not provide identical ordering across async suspension.', choice:'Read the ordering requirements before changing the mechanism.'},
  blocking: {title:'blocking work', meaning:'An operation that occupies its executing thread instead of suspending the Task.', detail:'A synchronous disk read may be brief or expensive. Finding one does not prove the UI freezes.', choice:'Inspect its executor and measured cost before deciding whether to change it.'},
  'ui-rule': {title:'a UI responsibility observation', meaning:'A calculation found in a View or ViewModel that needs context to understand its responsibility.', detail:'Formatting a value can belong in the UI. A reusable product rule may belong in the model. A text match cannot decide this.', choice:'Trace what the calculation means; do not label every conditional as misplaced business logic.'}
};
