const esc = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

// These are end-to-end source reviews, never conclusions from a keyword match.
export function concurrencyReview(checks) {
  const entries = checks ?? [];
  const counts = Object.fromEntries(['warning','managed','unresolved'].map(status => [status, entries.filter(c => c.status === status).length]));
  const labels = {warning:'⚠️ Warning', managed:'✓ Managed operation', unresolved:'Analysis incomplete'};
  const evidence = r => '<p class="path" title="'+esc(r.file)+'">'+esc(r.file.split('/').pop())+' · Line '+r.line+'</p><pre>'+r.excerpt.split('\n').map((line,i)=>'<span class="code-line '+(i===0?'code-focus':'')+'"><span class="line-number">'+(r.line+i)+'</span>'+esc(line)+'</span>').join('')+'</pre>';
  const detail = entries.map(c => '<details class="review"><summary style="color:var(--'+(c.status==='warning'?'amber':'accent')+')">'+labels[c.status]+' · '+esc(c.title)+'</summary>'+c.evidence.map(evidence).join('')+'<p><strong>Call path:</strong> '+esc(c.path)+'</p>'+[['Trigger',c.trigger],['Leaving the screen',c.navigation],['Another request',c.repetition],['Waiting and cancellation',c.lifetime],['Persistence / server outcome',c.effect],['Conclusion',c.conclusion],['Verification',c.verification]].map(([label,value])=>'<p><strong>'+label+':</strong> '+esc(value)+'</p>').join('')+'</details>').join('');
  return {counts, html:'<section class="results-panel" id="concurrency-warnings"><h2>⚠️ Concurrency Warnings</h2><p>View lifetime, repeated requests and independent Tasks.</p>'+(entries.length?'<p><strong>'+counts.warning+' warnings · '+counts.managed+' managed operations · '+counts.unresolved+' unresolved checks</strong></p><p class="small">Counts describe the operation reviews below, not all Tasks or a whole-project safety rating.</p>':'<p>No operation reviews imported. This does not mean there are no concurrency risks.</p>')+'<details><summary>What starts or cancels a Task?</summary><ul><li>Button + Task: another press can create another Task. It does not automatically cancel the first.</li><li>SwiftUI .task: SwiftUI requests cancellation when the View leaves its lifetime. A new View lifetime can start it again.</li><li>SwiftUI .task(id:): changing the ID cancels the previous Task and starts another. An ordinary redraw with unchanged identity and ID is not a restart trigger.</li><li>Cancellation is cooperative. It does not roll back a save or prove that a server rejected the request.</li><li>A retained, correctly managed independent Task is a valid design. Review its actual policy, not its classification alone.</li></ul></details>'+detail+'</section>'};
}
