const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function testQualityRating(scenarios) {
  const total=scenarios.length;
  const matched=scenarios.filter(s=>s.status==='identified').length;
  const score=total?Math.round(100*matched/total):null;
  return {score,stars:score===null?null:score/20,matched,total,colour:score===null?'var(--muted)':score>=80?'#75dfaa':'#ff8d8d'};
}
export function renderTestRating(review) {
  const r=testQualityRating(review.scenarios);
  const stars=r.score===null?'':'<div role="img" aria-label="'+r.stars+' out of 5 stars" style="display:inline-block;position:relative;font-size:2rem;line-height:1.2;white-space:nowrap;color:var(--line)"><span aria-hidden="true">★★★★★</span><span aria-hidden="true" style="position:absolute;inset:0 auto 0 0;overflow:hidden;width:'+r.score+'%;color:'+r.colour+'">★★★★★</span></div>';
  return '<div class="separation-gauge"><div><h3>Test quality rating</h3><p class="small muted">Reviewed scenarios only · '+r.matched+' of '+r.total+' have matching assertions</p><details><summary>How this rating works</summary><p class="small">Each reviewed scenario has equal weight. The score is matching scenarios divided by reviewed scenarios, rounded to 100. Stars use that same score: 80 / 100 = 4 / 5 stars. Green means 80–100; red means below 80.</p><p class="small">This is a limited measure of behavioural protection, not an exhaustive test-suite quality grade or code coverage. It does not measure assertion strength, flakiness or mutation resistance. Tests worth strengthening are listed separately. Even 100 / 100 only means every scenario in this review has matching assertions.</p></details></div><div style="text-align:center;flex-shrink:0"><strong style="display:block;font-size:2rem;color:'+r.colour+'">'+(r.score===null?'Not rated':r.score+' / 100')+'</strong>'+stars+'<span class="small muted" style="display:block">'+(r.stars===null?'No scenarios reviewed':r.stars+' / 5 stars')+'</span></div></div>';
}
export function renderTestReview(review) {
  const identified=review.scenarios.filter(s=>s.status==='identified').length;
  const code=r=>'<p class="path" title="'+esc(r.file)+'">'+esc(r.file.split('/').pop())+' · Line '+r.line+'</p><pre>'+r.excerpt.split('\n').map((l,i)=>'<span class="code-line'+(!i?' code-focus':'')+'"><span class="line-number">'+(r.line+i)+'</span>'+esc(l)+'</span>').join('')+'</pre>';
  const item=s=>'<details class="review"><summary>'+esc(s.title)+'</summary><p>'+esc(s.detail)+'</p>'+s.evidence.map(code).join('')+'</details>';
  return '<section id="test-quality" class="results-panel"><h2>Test quality review</h2>'+renderTestRating(review)+'<p class="small muted">'+esc(review.scope)+'</p><div class="score-grid"><div class="score"><strong>'+identified+' / '+review.scenarios.length+'</strong><span>Reviewed scenarios with matching assertions</span></div><div class="score"><strong>'+(review.scenarios.length-identified)+'</strong><span>Scenarios with no focused test identified</span></div><div class="score"><strong>'+review.concerns.length+'</strong><span>Tests worth strengthening</span></div></div><p class="small">One scenario means one behaviour group, not one test function. These counts are not code coverage or an exhaustive measure of missing tests. Matching assertions are source-reviewed; no per-scenario runtime mapping is claimed.</p><h3>⚠️ Tests worth strengthening</h3>'+review.concerns.map(item).join('')+(review.keep?'<h3>Useful tests to keep</h3>'+item(review.keep):'')+'<h3>Missing test scenarios</h3>'+review.scenarios.filter(s=>s.status!=='identified').map(item).join('')+'<h3>Existing behavioural protection</h3>'+review.scenarios.filter(s=>s.status==='identified').map(item).join('')+'<p class="small muted">No tests recommended for automatic removal. A simple-looking test can protect persistence, validation, conversion or API behaviour.</p></section>';
}
